### ISSUE TITLE
Enable/disable doorbell on pro readers

### ISSUE THREAD

**Issue by jbyerline** [hjdhjd/unifi-access#1]
The unifi access app and web allows us to enable or disable the doorbell manually. 

We would like to write a program to have this feature on a schedule. So that after hours the doorbell feature is disabled. 

Is it possible to get the api documentation for setting this value?

**Comment by hjdhjd** [comment]
Schedules are best done in the UniFi Access app or webUI. There's robust support for both - this really doesn't belong in the API that's a low-level interface to Access capabilities. Best of luck!
